// Generated by gencpp from file ur3/gripper_msg.msg
// DO NOT EDIT!


#ifndef UR3_MESSAGE_GRIPPER_MSG_H
#define UR3_MESSAGE_GRIPPER_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <control_msgs/GripperCommand.h>

namespace ur3
{
template <class ContainerAllocator>
struct gripper_msg_
{
  typedef gripper_msg_<ContainerAllocator> Type;

  gripper_msg_()
    : header()
    , gripper()  {
    }
  gripper_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gripper(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::control_msgs::GripperCommand_<ContainerAllocator>  _gripper_type;
  _gripper_type gripper;





  typedef boost::shared_ptr< ::ur3::gripper_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur3::gripper_msg_<ContainerAllocator> const> ConstPtr;

}; // struct gripper_msg_

typedef ::ur3::gripper_msg_<std::allocator<void> > gripper_msg;

typedef boost::shared_ptr< ::ur3::gripper_msg > gripper_msgPtr;
typedef boost::shared_ptr< ::ur3::gripper_msg const> gripper_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur3::gripper_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur3::gripper_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'control_msgs': ['/opt/ros/melodic/share/control_msgs/cmake/../msg'], 'ur3': ['/home/rafael/UR3/catkin_ur3/src/ur3/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur3::gripper_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur3::gripper_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur3::gripper_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur3::gripper_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur3::gripper_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur3::gripper_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur3::gripper_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc18072711edbb7f42a3cb3011b6a573";
  }

  static const char* value(const ::ur3::gripper_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc18072711edbb7fULL;
  static const uint64_t static_value2 = 0x42a3cb3011b6a573ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur3::gripper_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur3/gripper_msg";
  }

  static const char* value(const ::ur3::gripper_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur3::gripper_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"control_msgs/GripperCommand gripper\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: control_msgs/GripperCommand\n"
"float64 position\n"
"float64 max_effort\n"
;
  }

  static const char* value(const ::ur3::gripper_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur3::gripper_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripper_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur3::gripper_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur3::gripper_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gripper: ";
    s << std::endl;
    Printer< ::control_msgs::GripperCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR3_MESSAGE_GRIPPER_MSG_H
